/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import controller.ValidateDate;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modal.DOB;
import modal.Resume;
import modal.Work_Exp;

/**
 *
 * @author omkar
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    ButtonGroup gender, exp, joining;
    BufferedImage img;
    String img_path = "";
    Resume res;
    ArrayList<Resume> resList;
    
    public CreateJPanel(ArrayList<Resume> r) {
        initComponents();
        this.resList = r;
        res = new Resume();
        resList.add(res);
        gender = new ButtonGroup();
        gender.add(genderMaleRadioButton1);
        gender.add(genderFemaleRadioButton);
        
        exp = new ButtonGroup();
        exp.add(expYesRadioButton);
        exp.add(expNoRadioButton);
        
        joining = new ButtonGroup();
        joining.add(join1MonthRadioButton);
        joining.add(join2MonthRadioButton);
        joining.add(join3MonthRadioButton);
        joining.add(joinImmediateRadioButton);
        
        for (int i = 1950; i < 2016; i++) {
            yearCombo.addItem(i + "");
        }
        for (int i = 1; i < 13; i++) {
            monthCombo.addItem(i + "");
        }
        for (int i = 1; i < 32; i++) {
            dayCombo.addItem(i + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        nameLable = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        affiliationLabel = new javax.swing.JLabel();
        affiliationTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        designationTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        educationPanel = new javax.swing.JPanel();
        collegeLabel1 = new javax.swing.JLabel();
        collegeLabel = new javax.swing.JLabel();
        coll1TextField = new javax.swing.JTextField();
        coll2TextField = new javax.swing.JTextField();
        degree1Label = new javax.swing.JLabel();
        degree2Label = new javax.swing.JLabel();
        degree1TextField = new javax.swing.JTextField();
        degree2TextField = new javax.swing.JTextField();
        gpa1Label = new javax.swing.JLabel();
        gpa2label = new javax.swing.JLabel();
        gpa1TextField = new javax.swing.JTextField();
        gpa2TextField = new javax.swing.JTextField();
        passing1Label = new javax.swing.JLabel();
        passing2Label = new javax.swing.JLabel();
        passingTextField = new javax.swing.JTextField();
        passing2TextField = new javax.swing.JTextField();
        workPanel = new javax.swing.JPanel();
        organisation1Label = new javax.swing.JLabel();
        organisation2Label = new javax.swing.JLabel();
        org1TextField = new javax.swing.JTextField();
        org2TextField = new javax.swing.JTextField();
        duration1Label = new javax.swing.JLabel();
        duration2Label = new javax.swing.JLabel();
        dur1TextField = new javax.swing.JTextField();
        dur2TextField = new javax.swing.JTextField();
        designation1Label = new javax.swing.JLabel();
        designation2Label = new javax.swing.JLabel();
        desg1TextField = new javax.swing.JTextField();
        desg2TextField = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        addTextArea = new javax.swing.JTextArea();
        radioPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        expYesRadioButton = new javax.swing.JRadioButton();
        expNoRadioButton = new javax.swing.JRadioButton();
        genderLabel = new javax.swing.JLabel();
        genderFemaleRadioButton = new javax.swing.JRadioButton();
        genderMaleRadioButton1 = new javax.swing.JRadioButton();
        joiningLabel = new javax.swing.JLabel();
        join1MonthRadioButton = new javax.swing.JRadioButton();
        joinImmediateRadioButton = new javax.swing.JRadioButton();
        join3MonthRadioButton = new javax.swing.JRadioButton();
        join2MonthRadioButton = new javax.swing.JRadioButton();
        dayCombo = new javax.swing.JComboBox<>();
        monthCombo = new javax.swing.JComboBox<>();
        yearCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        CheckBoxCpp = new javax.swing.JCheckBox();
        CheckBoxJava = new javax.swing.JCheckBox();
        CheckBoxMsOffice = new javax.swing.JCheckBox();
        CheckBoxSql = new javax.swing.JCheckBox();
        CheckBoxWDev = new javax.swing.JCheckBox();
        CheckBoxTesting = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        headingLabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(0, 0, 102));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Create Resume");

        nameLable.setText("Name");

        addBtn.setText("Address");

        affiliationLabel.setText("Affiliation");

        phoneLabel.setText("Phone no");

        phoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneTextFieldKeyReleased(evt);
            }
        });

        photoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLabel.setText("Your Photo");
        photoLabel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Designation");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOB");

        educationPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        collegeLabel1.setText("College 1");

        collegeLabel.setText("College 2");

        degree1Label.setText("Degree 1");

        degree2Label.setText("Degree 2");

        gpa1Label.setText("GPA");

        gpa2label.setText("GPA");

        gpa1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gpa1TextFieldKeyReleased(evt);
            }
        });

        gpa2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gpa2TextFieldKeyReleased(evt);
            }
        });

        passing1Label.setText("Passing");

        passing2Label.setText("Passing");

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(collegeLabel1)
                    .addComponent(collegeLabel))
                .addGap(28, 28, 28)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coll1TextField)
                    .addComponent(coll2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degree1Label)
                    .addComponent(degree2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gpa2label)
                    .addComponent(gpa1Label))
                .addGap(27, 27, 27)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpa1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpa2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passing1Label)
                    .addComponent(passing2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passingTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passing2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collegeLabel1)
                    .addComponent(coll1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree1Label)
                    .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpa1Label)
                    .addComponent(gpa1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passing1Label)
                    .addComponent(passingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collegeLabel)
                    .addComponent(coll2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree2Label)
                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpa2label)
                    .addComponent(gpa2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passing2Label)
                    .addComponent(passing2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        workPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Experience", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        organisation1Label.setText("Organization");

        organisation2Label.setText("Organization");

        duration1Label.setText("Duration");

        duration2Label.setText("Duration");

        dur1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dur1TextFieldKeyReleased(evt);
            }
        });

        dur2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dur2TextFieldKeyReleased(evt);
            }
        });

        designation1Label.setText("Designation");

        designation2Label.setText("Designation");

        desg1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desg1TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(organisation1Label)
                    .addComponent(organisation2Label))
                .addGap(28, 28, 28)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(org1TextField)
                    .addComponent(org2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duration1Label)
                    .addComponent(duration2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dur1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dur2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(designation2Label)
                    .addComponent(designation1Label))
                .addGap(27, 27, 27)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desg1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desg2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisation1Label)
                    .addComponent(org1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration1Label)
                    .addComponent(dur1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designation1Label)
                    .addComponent(desg1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisation2Label)
                    .addComponent(org2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration2Label)
                    .addComponent(dur2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designation2Label)
                    .addComponent(desg2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(0, 255, 51));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        addTextArea.setColumns(20);
        addTextArea.setRows(5);

        radioPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("Experienced");

        expYesRadioButton.setText("Yes");
        expYesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expYesRadioButtonActionPerformed(evt);
            }
        });

        expNoRadioButton.setText("No");
        expNoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expNoRadioButtonActionPerformed(evt);
            }
        });

        genderLabel.setText("Gender");

        genderFemaleRadioButton.setText("Female");

        genderMaleRadioButton1.setText("Male");

        joiningLabel.setText("Joining");

        join1MonthRadioButton.setText("1 Month");

        joinImmediateRadioButton.setText("Immediate");

        join3MonthRadioButton.setText("3 Months");

        join2MonthRadioButton.setText("2 Months");

        javax.swing.GroupLayout radioPanelLayout = new javax.swing.GroupLayout(radioPanel);
        radioPanel.setLayout(radioPanelLayout);
        radioPanelLayout.setHorizontalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(genderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addComponent(expYesRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(expNoRadioButton)
                        .addGap(123, 123, 123))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addComponent(genderMaleRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(genderFemaleRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(joiningLabel)
                        .addGap(18, 18, 18)))
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(join2MonthRadioButton)
                    .addComponent(joinImmediateRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(join3MonthRadioButton)
                    .addComponent(join1MonthRadioButton))
                .addGap(38, 38, 38))
        );
        radioPanelLayout.setVerticalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderMaleRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderFemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joiningLabel)
                    .addComponent(joinImmediateRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(join1MonthRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(expYesRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expNoRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(radioPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(join3MonthRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(join2MonthRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Skllls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        CheckBoxCpp.setText("C++");

        CheckBoxJava.setText("Java");

        CheckBoxMsOffice.setText("MS Office");

        CheckBoxSql.setText("SQL");

        CheckBoxWDev.setText("Web Development");

        CheckBoxTesting.setText("Testing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxCpp)
                    .addComponent(CheckBoxJava))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxMsOffice)
                    .addComponent(CheckBoxSql))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxTesting)
                    .addComponent(CheckBoxWDev))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxCpp)
                    .addComponent(CheckBoxMsOffice)
                    .addComponent(CheckBoxWDev))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxSql)
                    .addComponent(CheckBoxTesting)
                    .addComponent(CheckBoxJava))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel4.setText("/");

        jLabel5.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLable)
                    .addComponent(affiliationLabel)
                    .addComponent(addBtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(phoneLabel)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(designationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(affiliationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(browseBtn))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(243, 243, 243))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(educationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(submitBtn)
                            .addGap(488, 488, 488)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameLable)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(addTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(affiliationLabel)
                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(designationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(radioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(educationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(workPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(submitBtn)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void desg1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desg1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desg1TextFieldActionPerformed

    private void expYesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expYesRadioButtonActionPerformed
        if (expYesRadioButton.isSelected()) {
            workPanel.setVisible(true);
        }
    }//GEN-LAST:event_expYesRadioButtonActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try {
            int year, month, day;
            
            year = Integer.parseInt(yearCombo.getSelectedItem().toString());//converting string to integer 
            month = Integer.parseInt(monthCombo.getSelectedItem().toString());
            day = Integer.parseInt(dayCombo.getSelectedItem().toString());
            if (ValidateDate.isDateValid(year, month, day)) {
                DOB dob = new DOB(year, month, day);
                
                if (nameTextField.getText().trim().length() != 0) {
                    res.setName(nameTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Enter your name");
                    return;
                }
                res.setDob(dob);
                
                if (addTextArea.getText().trim().length() != 0) {
                    res.setAddress1(addTextArea.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Enter your address");
                    return;
                }
                if (designationTextField.getText().trim().length() != 0) {
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Enter expected Designation");
                    return;
                }
                
                if (addTextArea.getText().trim().length() != 0) {
                    res.setDesg(designationTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Enter your text area");
                    return;
                }
                
                if (phoneTextField.getText().trim().length() != 0 && phoneTextField.getText().length() == 10) {
                    res.setPhNo(phoneTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Enter your 10 digits Phone Number");
                    return;
                }
                
                if (img_path.trim().length() != 0) {
                    res.setImage_path(img_path);
                } else {
                    JOptionPane.showMessageDialog(this, "Your image is required");
                    return;
                }
                if (affiliationTextField.getText().trim().length() != 0) {
                    res.setAffilation(affiliationTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Enter Affilation");
                    return;
                }

                //adding education
                if (Double.parseDouble(gpa1TextField.getText()) <= 4.0) {
                    modal.Education edu = new modal.Education(coll1TextField.getText(), degree1TextField.getText(), Double.parseDouble(gpa1TextField.getText()), passingTextField.getText());
                    res.addEdu(edu);
                } else {
                    JOptionPane.showMessageDialog(this, "GPA must be less than 4.0");
                    return;
                }
                if (coll2TextField.getText().trim().length() != 0 && degree2TextField.getText().trim().length() != 0) {
                    if (Double.parseDouble(gpa2TextField.getText()) <= 4.0) {
                        modal.Education edu1 = new modal.Education(coll2TextField.getText(), degree2TextField.getText(), Double.parseDouble(gpa2TextField.getText()), passing2TextField.getText());
                        res.addEdu(edu1);
                    } else {
                        JOptionPane.showMessageDialog(this, "GPA must be less than 4.0");
                        return;
                    }
                }

                //adding work
                if (expYesRadioButton.isSelected()) {
                    if (org1TextField.getText().trim().length() != 0 && desg1TextField.getText().trim().length() != 0) {
                        Work_Exp work = new Work_Exp(org1TextField.getText(), desg1TextField.getText(), Double.parseDouble(dur1TextField.getText()));
                        res.addWork(work);
                    } else {
                        JOptionPane.showMessageDialog(this, "Add work Experience");
                    }
                    if (org2TextField.getText().trim().length() != 0 && desg2TextField.getText().trim().length() != 0) {
                        Work_Exp work = new Work_Exp(org2TextField.getText(), desg2TextField.getText(), Double.parseDouble(dur2TextField.getText()));
                        res.addWork(work);
                    }
                    
                } else if (expNoRadioButton.isSelected()) {
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Do you have experience. Please select");
                    return;
                }

                //adding gender
                if (genderMaleRadioButton1.isSelected()) {
                    res.setGender("Male");
                } else if (genderFemaleRadioButton.isSelected()) {
                    res.setGender("Female");
                } else {
                    JOptionPane.showMessageDialog(this, "Please select Your gender");
                    return;
                }

                //adding joining
                if (joinImmediateRadioButton.isSelected()) {
                    res.setJoining(joinImmediateRadioButton.getText());
                } else if (join1MonthRadioButton.isSelected()) {
                    res.setJoining(join1MonthRadioButton.getText());
                } else if (join2MonthRadioButton.isSelected()) {
                    res.setJoining(join2MonthRadioButton.getText());
                } else if (join3MonthRadioButton.isSelected()) {
                    res.setJoining(join3MonthRadioButton.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Select Joining Option");
                    return;
                }

                //adding skills
                if (CheckBoxCpp.isSelected()) {
                    res.addSkills("C++");
                }
                if (CheckBoxJava.isSelected()) {
                    res.addSkills("Java");
                }
                if (CheckBoxMsOffice.isSelected()) {
                    res.addSkills("MS OFfice");
                }
                if (CheckBoxSql.isSelected()) {
                    res.addSkills("SQL");
                }
                if (CheckBoxTesting.isSelected()) {
                    res.addSkills("Testing");
                }
                if (CheckBoxWDev.isSelected()) {
                    res.addSkills("Web Development");
                }
                System.out.println("asd");
                JOptionPane.showMessageDialog(this, "Submitted. Click on create button to add another");
                
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Valid DateF");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Something went wrong");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        selectFile();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void phoneTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextFieldKeyReleased
        char c = evt.getKeyChar();
        int value = (int) c;
        System.out.println("" + value);
        if ((value >= 48 && value <= 57) || value == 8) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Only numbers are allowed. Clearing text box");
            phoneTextField.setText("");
        }
        

    }//GEN-LAST:event_phoneTextFieldKeyReleased

    private void gpa1TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpa1TextFieldKeyReleased
        char c = evt.getKeyChar();
        int value = (int) c;
        
        if ((value >= 48 && value <= 57) || value == 8 || value == 46) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Only  decimal numbers are allowed. Clearing text box");
            gpa1TextField.setText("");
        }
    }//GEN-LAST:event_gpa1TextFieldKeyReleased

    private void gpa2TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpa2TextFieldKeyReleased
        char c = evt.getKeyChar();
        int value = (int) c;
        
        if ((value >= 48 && value <= 57) || value == 8 || value == 46) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Only decimal numbers are allowed. Clearing text box");
            gpa2TextField.setText("");
        }
    }//GEN-LAST:event_gpa2TextFieldKeyReleased

    private void expNoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expNoRadioButtonActionPerformed
        if (expNoRadioButton.isSelected()) {
            workPanel.setVisible(false);
        }
    }//GEN-LAST:event_expNoRadioButtonActionPerformed

    private void dur1TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dur1TextFieldKeyReleased
        char c = evt.getKeyChar();
        int value = (int) c;
        
        if ((value >= 48 && value <= 57) || value == 8 || value == 46) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Only  decimal numbers are allowed. Clearing text box");
            dur1TextField.setText("");
        }
    }//GEN-LAST:event_dur1TextFieldKeyReleased

    private void dur2TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dur2TextFieldKeyReleased
        char c = evt.getKeyChar();
        int value = (int) c;
        
        if ((value >= 48 && value <= 57) || value == 8 || value == 46) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Only  decimal numbers are allowed. Clearing text box");
            dur2TextField.setText("");
        }
    }//GEN-LAST:event_dur2TextFieldKeyReleased
    private void selectFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);// needed false to selec limited extension files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg");// only jpg files.
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.showOpenDialog(this);
        
        try {
            img = ImageIO.read(fileChooser.getSelectedFile());
            int w = img.getWidth();
            int h = img.getHeight();
            
            if (w > 150 || h > 150) {
                JOptionPane.showMessageDialog(this, "Image must be of maximum 150 x 150 pixels resolution.. Try again");
                selectFile();
                
            } else {
                ImageIcon icon = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath());
                img_path = fileChooser.getSelectedFile().getAbsolutePath();
                photoLabel.setIcon(icon);
            }
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Not valid image. Try again");
            selectFile();
            ex.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxCpp;
    private javax.swing.JCheckBox CheckBoxJava;
    private javax.swing.JCheckBox CheckBoxMsOffice;
    private javax.swing.JCheckBox CheckBoxSql;
    private javax.swing.JCheckBox CheckBoxTesting;
    private javax.swing.JCheckBox CheckBoxWDev;
    private javax.swing.JLabel addBtn;
    private javax.swing.JTextArea addTextArea;
    private javax.swing.JLabel affiliationLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JButton browseBtn;
    private javax.swing.JTextField coll1TextField;
    private javax.swing.JTextField coll2TextField;
    private javax.swing.JLabel collegeLabel;
    private javax.swing.JLabel collegeLabel1;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JLabel degree1Label;
    private javax.swing.JTextField degree1TextField;
    private javax.swing.JLabel degree2Label;
    private javax.swing.JTextField degree2TextField;
    private javax.swing.JTextField desg1TextField;
    private javax.swing.JTextField desg2TextField;
    private javax.swing.JLabel designation1Label;
    private javax.swing.JLabel designation2Label;
    private javax.swing.JTextField designationTextField;
    private javax.swing.JTextField dur1TextField;
    private javax.swing.JTextField dur2TextField;
    private javax.swing.JLabel duration1Label;
    private javax.swing.JLabel duration2Label;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JRadioButton expNoRadioButton;
    private javax.swing.JRadioButton expYesRadioButton;
    private javax.swing.JRadioButton genderFemaleRadioButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JRadioButton genderMaleRadioButton1;
    private javax.swing.JLabel gpa1Label;
    private javax.swing.JTextField gpa1TextField;
    private javax.swing.JTextField gpa2TextField;
    private javax.swing.JLabel gpa2label;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton join1MonthRadioButton;
    private javax.swing.JRadioButton join2MonthRadioButton;
    private javax.swing.JRadioButton join3MonthRadioButton;
    private javax.swing.JRadioButton joinImmediateRadioButton;
    private javax.swing.JLabel joiningLabel;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField org1TextField;
    private javax.swing.JTextField org2TextField;
    private javax.swing.JLabel organisation1Label;
    private javax.swing.JLabel organisation2Label;
    private javax.swing.JLabel passing1Label;
    private javax.swing.JLabel passing2Label;
    private javax.swing.JTextField passing2TextField;
    private javax.swing.JTextField passingTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JPanel radioPanel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JPanel workPanel;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables
}
